### ISSUE TITLE
incorrect behavior "$problem-matcher-sjasmplus"

### ISSUE THREAD

**Issue by Tolik-Trek** [maziac/asm-code-lens#83] opened 2022-11-29 09:29 UTC
incorrect behavior with parameter "--fullpath" for sjasmplus. Link to problem file goes to ${workspaceFolder} + fullpath/filename

**Comment by maziac** [comment] 2022-11-29 16:11
Just checked: on macOS it seems to work.
Are you on Windows?

**Comment by maziac** [comment] 2022-11-29 16:26
I need more context. On Windows it works for me as well.
Could you put your project here?

**Comment by Tolik-Trek** [comment] 2022-11-29 16:38
> I need more context. On Windows it works for me as well.

MacOS. Maybe language specific symbols is matter

**Comment by Tolik-Trek** [comment] 2022-11-29 17:01
<img width="1916" alt="image" src="https://user-images.githubusercontent.com/85737314/204594024-1c7167bb-0eed-4b02-ba79-c87d1bdf4860.png">

<img width="1382" alt="image" src="https://user-images.githubusercontent.com/85737314/204594153-345c39be-c752-49c9-b5f3-1781b6b8d935.png">

**Comment by maziac** [comment] 2022-11-29 17:27
Which version of sjasmplus are you using?

~~~
 --fullpath               Show full path to file in errors
  Note: the "fullpath" starts from current working directory, not from file system
		root (the MS_VS build was fixed to behave this way since v1.15.0)
~~~

Could it be that you are using a pre 1.15 version?

**Comment by Tolik-Trek** [comment] 2022-11-29 18:54
> Which version of sjasmplus are you using?
> 
> ```
>  --fullpath               Show full path to file in errors
>   Note: the "fullpath" starts from current working directory, not from file system
> 		root (the MS_VS build was fixed to behave this way since v1.15.0)
> ```
> 
> Could it be that you are using a pre 1.15 version?

SjASMPlus Z80 Cross-Assembler v1.20.1 (https://github.com/z00m128/sjasmplus)

**Comment by maziac** [comment] 2022-11-29 21:42
> Any project

Just tried your Bug_Test project with the tasks.json you provided above, but still no absolute paths:
![Bildschirmfoto 2022-11-29 um 22 40 04](https://user-images.githubusercontent.com/3081973/204653785-34ad4335-3c2d-403d-8e42-474a47ef8d95.jpg)

Could you maybe try a folder without Cyrillic characters and which is not a Google Drive, to rule that out.

**Comment by maziac** [comment] 2022-11-30 16:56
What I don't understand is: already the sjasmplus output is different: ours are absolute paths, mine is with relative paths. Despite the same arguments.
Could you maybe try directly from the command line.
Maybe sjasmplus is not started in the project's root directory but somewhere else. (wild guess)

**Comment by Tolik-Trek** [comment] 2022-11-30 17:03
> Maybe sjasmplus is not started in the project's root directory but somewhere else. (wild guess)

Yes. it is not in the project's root directory. One sjasmplus for all projects

**Comment by maziac** [comment] 2022-11-30 17:46
Yes. But what I mean is that you maybe don't assemble from the project root directory.

**Comment by maziac** [comment] 2022-11-30 19:18
OK. I found the difference:
It's the file to assemble for sjasmplus.
If I use ```${workspaceFolder}/MAIN.asm``` (the full path) the result contains also the full path.
If I just use ```MAIN.asm``` (the relative path) the result is also a relative path.

Now that I can reproduce, let's see what I can do about it.

**Comment by maziac** [comment] 2022-11-30 19:51
Should be fixed now. Could you please try the attached vsix.
[asm-code-lens-2.0.2-rc1.vsix.zip](https://github.com/maziac/asm-code-lens/files/10126776/asm-code-lens-2.0.2-rc1.vsix.zip)

**Closed** 2022-11-30 19:54 UTC

**Comment by Tolik-Trek** [comment] 2022-12-01 06:16
> Should be fixed now. Could you please try the attached vsix. [asm-code-lens-2.0.2-rc1.vsix.zip](https://github.com/maziac/asm-code-lens/files/10126776/asm-code-lens-2.0.2-rc1.vsix.zip)

Excellent! You are just a magician)) It works, thanks)))
